<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>dl-extract</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Deadlock.Format/Deadlock.Format.csproj" />
    <ProjectReference Include="../Deadlock.Contracts/Deadlock.Contracts.csproj" />
  </ItemGroup>
</Project>
